-- ROWNUM : 순번을 정해놓은 SUPO COLUMN이다.
-- 조회되는 행의 수를 제한할때 사용
SELECT ROWNUM bno, title, writer, content
FROM board
WHERE ROWNUM > 0 AND ROWNUM <= 10
-- WHERE ROWNUM > 10 AND ROWNUM <= 20 1을 포함해야 조회됨
ORDER BY bno;

-- 11에서 20번까지 검색 (중첩쿼리) 괄호를 사용
SELECT * FROM
(SELECT ROWNUM RN, bno, title, writer, content 
FROM board)
WHERE RN > 10 AND RN <= 20;
-- WHERE ROWNUM > 10 AND ROWNUM <= 20 1을 포함해야 조회됨

-- ROWNUM의 올바른 사용
CREATE TABLE EX_SCORE(
    NAME    VARCHAR2(10),
    SCORE   NUMBER
);

INSERT INTO EX_SCORE VALUES('김하나', 94);
INSERT INTO EX_SCORE VALUES('이하나', 100);
INSERT INTO EX_SCORE VALUES('박하나', 97);
INSERT INTO EX_SCORE VALUES('정하나', 77);
INSERT INTO EX_SCORE VALUES('조하나', 87);
INSERT INTO EX_SCORE VALUES('안하나', 91);
INSERT INTO EX_SCORE VALUES('유하나', 66);
INSERT INTO EX_SCORE VALUES('오하나', 85);
INSERT INTO EX_SCORE VALUES('한하나', 80);
INSERT INTO EX_SCORE VALUES('성하나', 95);

SELECT * FROM EX_SCORE;

-- 틀린 사용
SELECT ROWNUM, NAME, SCORE
    FROM EX_SCORE
    WHERE ROWNUM <= 5
    ORDER BY SCORE DESC;
     
-- 올바른 사용(서브 쿼리 방식 - 인라인 뷰)
SELECT * FROM
(SELECT ROWNUM, NAME, SCORE
    FROM EX_SCORE
    ORDER BY SCORE DESC)
WHERE ROWNUM <= 5;
